apiVersion: v1
kind: Pod
metadata:
  name: shuffle-lunch
  labels:
    app: shuffle-lunch
spec:
  containers:
  - name: shuffle-lunch
    image: practice/shuffle-lunch:latest
    imagePullPolicy: IfNotPresent
    workingDir: /app
    command:
      - './entrypoint.sh'
    volumeMounts:
    - name: app
      mountPath: /app
    ports:
    - containerPort: 3000
    env:
    - name: DB_HOST
      value: postgresql
    - name: DB_USER
      value: postgres
    - name: DB_PASSWORD
      value: password
    - name: BUNDLE_PATH
      value: vendor/bundle
    - name: BUNDLE_JOBS
      value: '4'
  volumes:
  - name: app
    hostPath:
      path: /Users/first/Documents/Projects/orchestration-practice/shuffle-lunch/app
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    app: shuffle-lunch
spec:
  containers:
  - name: postgresql
    image: postgres:10.5-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: pg-data
      mountPath: /var/lib/postgresql/data
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: password
  volumes:
  - name: pg-data
    emptyDir: {}
    # hostPath:
    #   path: /Users/first/Documents/Projects/orchestration-practice/shuffle-lunch/data/postgresql
    #   type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: shuffle-lunch
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: shuffle-lunch
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: shuffle-lunch
